services:
  litellm:
    image: ghcr.io/berriai/litellm-database:main-v1.74.7-stable.patch.2
    ports:
      - 4000:4000
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/litellm
    volumes:
      - ./config.yaml:/app/config.yaml
    command: --config /app/config.yaml
  postgres:
    image: postgres:16
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=litellm
